//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AM
{
public class GameEvent
{
		public GEventType Type;
		public string Data;
		public ClassController MainChar;

		public GameEvent (GEventType type, ClassController mainChar)
		{
			Type = type;
			MainChar = mainChar;
		}

}
}

